apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-s1zf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-s1zf
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-s1zf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-s1zf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-s1zf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/happy-depl-rbjp-tenant/appstudio/dc-metro-map-s1zf@sha256:f4a75a9e6cf61a4940718969d90cfe71e7ae4b6c731c94136d51d3e0a39ba8fc
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
